apiVersion: core.openfeature.dev/v1beta1
kind: Flagd
metadata:
  name: flagd
spec:
  featureFlagSource: {{ .Values.tenant }}-source
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.flagd.replicas }}
  {{- end }}
  serviceType: {{ .Values.flagd.serviceType }}
